In [ ]:
import numpy as np
import pandas as pd
import re

In [ ]:
df = pd.read_csv("tamil_sentiment_full_train.tsv", sep='\t')


In [ ]:
#df = df_all.sample(frac=1).reset_index(drop=True)
print(df)

#data set is restriced to 500
#df = df[:500]

df.head()

                                                    text        category
0      Vani bhojam fans hit like solli 500 like Vangi...   unknown_state
1                           I love you ajith very I like        Positive
2      ennaya trailer Ku mudi Ellam nikkudhu... Vera ...        Positive
3               Vijay Annaa  Ur Maassssss Therrrrriiiiii        Positive
4                            நம்ப நடே நாசாமா தான் போச்சி        Negative
...                                                  ...             ...
35651  ஒருவர் செய்த தவறுக்காக எல்லாரையும் பழி போடுவது...  Mixed_feelings
35652  Repeated Mode to Watching Theri Trailer & Ther...        Positive
35653  yeevanikuachu  pula kutti erudhal oodi poyidu....        Negative
35654                 She is looking like laughing budha        Positive
35655                   NORTH OR SOUTH KGF IS THE BEST!!        Positive

[35656 rows x 2 columns]


text       category
0  Vani bhojam fans hit like solli 500 like Vangi...  unknown_state
1                       I love you ajith very I like       Positive
2  ennaya trailer Ku mudi Ellam nikkudhu... Vera ...       Positive
3           Vijay Annaa  Ur Maassssss Therrrrriiiiii       Positive
4                        நம்ப நடே நாசாமா தான் போச்சி       Negative

In [ ]:
X = df['text']
y = df['category']
X

0        Vani bhojam fans hit like solli 500 like Vangi...
1                             I love you ajith very I like
2        ennaya trailer Ku mudi Ellam nikkudhu... Vera ...
3                 Vijay Annaa  Ur Maassssss Therrrrriiiiii
4                              நம்ப நடே நாசாமா தான் போச்சி
                               ...                        
35651    ஒருவர் செய்த தவறுக்காக எல்லாரையும் பழி போடுவது...
35652    Repeated Mode to Watching Theri Trailer & Ther...
35653    yeevanikuachu  pula kutti erudhal oodi poyidu....
35654                   She is looking like laughing budha
35655                     NORTH OR SOUTH KGF IS THE BEST!!
Name: text, Length: 35656, dtype: object

In [ ]:
# Preprocessing
processed_tweets = []
 
for tweet in range(0, len(X)):  
    # Remove all the special characters
    processed_tweet = re.sub(r'\W', ' ', str(X[tweet]))
 
    # remove all single characters
    processed_tweet = re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_tweet)
 
    # Remove single characters from the start
    processed_tweet = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_tweet) 
 
    # Substituting multiple spaces with single space
    processed_tweet= re.sub(r'\s+', ' ', processed_tweet, flags=re.I)
 
    # Removing prefixed 'b'
    processed_tweet = re.sub(r'^b\s+', '', processed_tweet)
 
    # Converting to Lowercase
    processed_tweet = processed_tweet.lower()
 
    processed_tweets.append(processed_tweet)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer  
tfidfconverter = TfidfVectorizer(max_features=2000)  
X = tfidfconverter.fit_transform(processed_tweets).toarray()
print(X.shape)

(35656, 2000)


In [ ]:
#from sklearn.model_selection import train_test_split  
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train = X
y_train = y

In [ ]:
# Handling Validation data
#df_all = pd.read_csv("tamil_sentiment_full_dev.tsv", sep='\t')
#df = df_all.sample(frac=1).reset_index(drop=True)
#print(df)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
text_classifier = RandomForestClassifier(n_estimators=100, random_state=0)  
text_classifier.fit(X_train, y_train)
 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
df_val = pd.read_csv("tamil_sentiment_full_dev.tsv", sep='\t')
print(df_val)


                                                   text        category
0     @0:40 songsuperb..kamallllla..  I'm waiting fo...   unknown_state
1     கணத்ததோர் அகமுடையார் சார்பாக  படம் வெற்றி அடைய...        Positive
2     Thalavia neenga veera level boss and neega tha...        Positive
3                 Oru padam patha fell.vera level music        Positive
4     Hairstyle than mattama iruku. Adhu mattum math...   unknown_state
...                                                 ...             ...
3957  நாடக காதல் மிகப்பெரிய தவறு. இதை தான் இந்த படம்...        Positive
3958                          So long to see you suriya       not-Tamil
3959  Super  sK  ettan adipoli makkalle dec20  waiti...  Mixed_feelings
3960      Minimum 50m viewa vara veppoma all thala fans        Positive
3961                     Vera Vera level da version 2.0        Positive

[3962 rows x 2 columns]


In [ ]:
X_val = df_val['text']
y_val = df_val['category']
# Preprocessing
val_processed_tweets = []
 
for tweet in range(0, len(X_val)):  
    # Remove all the special characters
    val_processed_tweet = re.sub(r'\W', ' ', str(X_val[tweet]))
 
    # remove all single characters
    val_processed_tweet = re.sub(r'\s+[a-zA-Z]\s+', ' ', val_processed_tweet)
 
    # Remove single characters from the start
    val_processed_tweet = re.sub(r'\^[a-zA-Z]\s+', ' ', val_processed_tweet) 
 
    # Substituting multiple spaces with single space
    val_processed_tweet= re.sub(r'\s+', ' ', val_processed_tweet, flags=re.I)
 
    # Removing prefixed 'b'
    val_processed_tweet = re.sub(r'^b\s+', '', val_processed_tweet)
 
    # Converting to Lowercase
    val_processed_tweet = val_processed_tweet.lower()
 
    val_processed_tweets.append(val_processed_tweet)
print(val_processed_tweets)

[' 0 40 songsuperb kamallllla m waiting for dis song you', 'கணத தத ர அகம ட ய ர ச ர ப க படம வ ற ற அட ய வ ழ த த கள ', 'thalavia neenga veera level boss and neega thaan marana mass', 'oru padam patha fell vera level music', 'hairstyle than mattama iruku adhu mattum mathirukalaam teaser paakurapo vettaikaran padam maari theridhu ', 'ப ண ப ள ள கள ப ற ற அப ப க கள க க க ட ம பங கள க க மட ட ம த ன த ர ய ம க தல ந டக த ர மணத த ன ல ஏற பட ம வல வ தன அவம னங கள நன ற அண ண mohan க தல ந டக த ர மணத த ம ட ப ட ட த ல உற த ததற க ', 'school competition la vara speech maadhiri irukkuda', 'க ங க ந ட ட மக கள மத த ய ல ப ர ம வ ற ற யட ய ம இந த படம ', 'i am sri lanka but love youu indiaaaaaaaaaaaaa', 'last dialogue sema actually niraya peru atha than pantrangaa', 'த வந த ரக ல மக கள ச ர ப க படம வ ற ற அட ய வ ழ த த கள அண ண ', 'worst trailer ever seen kalaignarin pasa kiligal padathoda trailer ithuku evlo mel ', 'views 56k ku kattuthu like 102 ku kattuthu', 'sema yaara ematha pakkara ithu 92 super jayam ravi and yogi babu

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer  
tfidfconv = TfidfVectorizer(max_features=2000)  
X_val = tfidfconv.fit_transform(val_processed_tweets).toarray()
print(X_val.shape)

(3962, 2000)


In [ ]:
X_test = X_val
y_test = y_val
predictions = text_classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
 
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  
print(accuracy_score(y_test, predictions))

[[  19   46  227   60   86]
 [  26   55  261   68   70]
 [  67  315 1138  337  400]
 [   6   17   86   51   16]
 [  24   70  323   86  108]]
                precision    recall  f1-score   support

Mixed_feelings       0.13      0.04      0.07       438
      Negative       0.11      0.11      0.11       480
      Positive       0.56      0.50      0.53      2257
     not-Tamil       0.08      0.29      0.13       176
 unknown_state       0.16      0.18      0.17       611

      accuracy                           0.35      3962
     macro avg       0.21      0.23      0.20      3962
  weighted avg       0.37      0.35      0.35      3962

0.3460373548712771


In [ ]:
df_test = pd.read_csv("tamil_sentiment_full_test_withoutlabels.tsv", sep='\t')
test_X_test = df_test['text']
# Preprocessing
test_processed_tweets = []
 
for tweet in range(0, len(test_X_test)):  
    # Remove all the special characters
    test_processed_tweet = re.sub(r'\W', ' ', str(test_X_test[tweet]))
 
    # remove all single characters
    test_processed_tweet = re.sub(r'\s+[a-zA-Z]\s+', ' ', test_processed_tweet)
 
    # Remove single characters from the start
    test_processed_tweet = re.sub(r'\^[a-zA-Z]\s+', ' ', test_processed_tweet) 
 
    # Substituting multiple spaces with single space
    test_processed_tweet= re.sub(r'\s+', ' ', test_processed_tweet, flags=re.I)
 
    # Removing prefixed 'b'
    test_processed_tweet = re.sub(r'^b\s+', '', test_processed_tweet)
 
    # Converting to Lowercase
    test_processed_tweet = test_processed_tweet.lower()
 
    test_processed_tweets.append(test_processed_tweet)
print(test_processed_tweets)

['வ ர ச ங க ந தர ச ர ப க இந த த ர ப படம வ ற ற ப ற வ ழ த த க கள இயக க னர ம கன அவர கள க க எங கள சம த யத த ன ச ர ப க வ ழ த த க கள ', 'teruk ah irukku mokke movie waste of time', 'manitha samuthaayam amaipil irunthu intha padam vetri adaiya vaalthukal', 'jj mam we miss u', 'subtitle me traller dekhne wale like karo', 'என னட இத ச ஸ டத த வச ச ச ய ஞ ச ட ட ன ங க ', 'ஒர ஆள உன ன எத ர த த ந வளர அத வ பல க ட டம உன ன எத த த கதர த ன ந வளந த ட டன அர த தம இப படம ந டக க தல க க ம உன ம க தல ஆனவ க ல ச ய வ ர க க ச ட ட அட ய க இர க க ம என எத ர ப ர க கப பட க றத வ ற ற ப ற வ ழ த த க கள ', 'ayutha ezhuthu 2 semmai waiting', '1 50 to 1 55 vera level mass', '16 varushama rajini arasiyalukku varuvennu sollittu irukkaaru aaana innum varala ha ha ha', 'makkal selvan fan from tollywood we need makkal in tollywood', 'str and arun vj vera leavel', 'thala hardwork dedication in the movie next level thalaaaaaaaaaaa', 'raniji arasial idhu 96 semma bro', 'ந ட ர ச ர ப க படம வ ற ற ப ற வ ழ த த க கள ', 'ப ர க கவ க ல உட ய ர கள ன 

In [ ]:
tfidfconv_test = TfidfVectorizer(max_features=2000)  
test_data = tfidfconv_test.fit_transform(test_processed_tweets).toarray()
test_predictions = text_classifier.predict(test_data)

df_test['label']=test_predictions
print(df_test)
df_test.to_csv('output_final.tsv',sep='\t', index= False)




            id  ...          label
0        Tam_1  ...       Positive
1        Tam_2  ...       Positive
2        Tam_3  ...       Positive
3        Tam_4  ...       Positive
4        Tam_5  ...       Positive
...        ...  ...            ...
4397  Tam_4398  ...       Positive
4398  Tam_4399  ...       Positive
4399  Tam_4400  ...      not-Tamil
4400  Tam_4401  ...  unknown_state
4401  Tam_4402  ...       Negative

[4402 rows x 3 columns]
